// Code generated by "stringer -type=parserTokenType"; DO NOT EDIT.

package nestext

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[undefined-0]
	_ = x[eof-1]
	_ = x[emptyDocument-2]
	_ = x[docRoot-3]
	_ = x[listKey-4]
	_ = x[listKeyMultiline-5]
	_ = x[stringMultiline-6]
	_ = x[dictKeyMultiline-7]
}

const _parserTokenType_name = "undefinedeofemptyDocumentdocRootlistKeylistKeyMultilinestringMultilinedictKeyMultiline"

var _parserTokenType_index = [...]uint8{0, 9, 12, 25, 32, 39, 55, 70, 86}

func (i parserTokenType) String() string {
	if i < 0 || i >= parserTokenType(len(_parserTokenType_index)-1) {
		return "parserTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parserTokenType_name[_parserTokenType_index[i]:_parserTokenType_index[i+1]]
}
